# // docker-compose.yml
services:
  db:
    image: postgres:15-alpine
    pull_policy: if_not_present
    ports:
      - "5432:5432"
    networks:
      - private_net
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  piston:
    image: ghcr.io/engineer-man/piston:latest
    pull_policy: if_not_present
    privileged: true
    ports:
      - "2000:2000"
    networks:
      - private_net
    volumes:
      - piston_data:/piston
    restart: unless-stopped



 
networks:
  public_net:
  private_net:

volumes:
  pgdata:
  piston_data:
